apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-deploy-applicationset
  namespace: gitops
spec:
  project: default
  source:
    repoURL: https://github.com/UsmanAsim/test-gitops.git
    targetRevision: main
    path: "ACE/testing/overlays/dev/"
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true  
      selfHeal: true