apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: react-applicationset
spec:
  destination:
    name: ''
    namespace: gitops
    server: 'https://kubernetes.default.svc'
  source:
    path: ACE/testing/overlays/dev/
    repoURL: 'https://github.com/UsmanAsim/test-gitops.git'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
project: default
source:
  repoURL: 'https://github.com/UsmanAsim/test-gitops.git'
  path: ACE/testing/overlays/dev/
  targetRevision: HEAD
destination:
  server: 'https://kubernetes.default.svc'
  namespace: dev