apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-deployment
spec:
  template:
    spec:
      containers:
        image: usmanasim11/cicd:react-app-cc9b274abd7d7c2d8f598df7313475a3ddde76de