apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-deploy
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: gitops
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ACE/argocd/testing/
    repoURL: https://github.com/UsmanAsim/test-gitops.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true